admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_hello:
    path: /hello/{name}
    defaults: { _controller: AdminBundle:Default:hello, name: "yangjianjian" }
    requirements: { name: "[a-zA-Z]+" }

admin_show_template:
    path: /template
    defaults: { _controller: AdminBundle:Default:template }

admin_validation:
    path: /validation
    defaults: { _controller: AdminBundle:Default:validation }

admin_form:
    path: /form
    defaults: { _controller: AdminBundle:Default:form }

admin_form_result:
    path: /form_result/{name}/{price}
    defaults: { _controller: AdminBundle:Default:formres, name: "null", price: 123 }

admin_admin:
    path: /admin
    defaults: { _controller: AdminBundle:Default:admin }

admin_login:
    path: /login
    defaults: { _controller: AdminBundle:Default:login }

admin_check:
    path: /check

admin_logout:
    path: /logout

admin_service:
    path: /service
    defaults: { _controller: AdminBundle:Default:service }
