app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    host: zywj.com
        
bbs:
    resource: "@BbsBundle/Resources/config/routing.yml"
    prefix:   /bbs
    host: zywj.com

assistant:
    resource: "@AssistantBundle/Resources/config/routing.yml"
    host: my.zywj.com

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    host: admin.zywj.com
