app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    host: "%hosts.app_domain%"
        
bbs:
    resource: "@BbsBundle/Resources/config/routing.yml"
    prefix:   /bbs
    host: "%hosts.app_domain%"

assistant:
    resource: "@AssistantBundle/Resources/config/routing.yml"
    host: "%hosts.my_domain%"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    host: "%hosts.admin_domain%"
