# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
services:
    cpo.admin_provider:
        class: AdminBundle\Security\User\AdminProvider
    cpo.user_provider:
        class: AppBundle\Security\User\UserProvider
    cs_user.login_listener:
        class: AdminBundle\Security\User\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

security:
    encoders:
        AdminBundle\Security\User\CpoAdmin: 
            algorithm:           sha512
            encode_as_base64:    false
            iterations:          1

        AppBundle\Security\User\CpoUser: 
            algorithm:           sha512
            encode_as_base64:    false
            iterations:          1

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        admin_custom_provider:
            id: cpo.admin_provider
        user_custom_provider:
            id: cpo.user_provider

    firewalls:
        admin:
            host: %hosts.admin_domain%
            provider: admin_custom_provider
            pattern: ^/
            anonymous: true
            form_login:
                login_path: admin_login
                check_path: admin_check
                default_target_path: admin_admin
                username_parameter: form[username]
                password_parameter: form[password]

                # csrf token options
                csrf_provider: security.csrf.token_manager
                csrf_parameter: _csrf_token

            logout:
                path: admin_logout
                target: admin_homepage

        app:
            host: %hosts.app_domain%
            provider: user_custom_provider
            pattern: ^/
            anonymous: true
            form_login:
                login_path: user_login
                check_path: user_check
                default_target_path: user_admin
                csrf_provider: security.csrf.token_manager

            logout:
                path: user_logout
                target: user_homepage
    access_control:
        user_login:
            host: %host.app_domain%
            path: ^/admin
            roles: ROLE_ADMIN
        admin_login:
            host: %host.app_domain%
            path: ^/admin
            roles: ROLE_USER
            
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
